### PR TITLE
Fix #257. Draw sprite does not like bad y coordinates.

### LINKED ISSUE #257: Crash when buying vehicles (trains DO work tho)
**OS:**  Manjaro Linux 4.20.3-1x64
**Version:**  18.02-454
**Commit/Build:**  c42e59c

Buying any truck, bus, boat or plane results on a segmentation fault. Yes, I checked the options mentioned on #219, still crashing

**Steps to reproduce:**
1. Buy vehicle
```

 ./openloco
OpenLoco, v18.02-454 (c42e59c on master, DEBUG)
CreateRectRgn(0, 0, 1, 1)
Create progress bar
SendMessage(PBM_SETRANGE, 256)
SendMessage(PBM_SETSTEP, 1)
SendMessage(PBM_SETPOS, 30)
OpenMutexA(0x1f0001, 0, Locomotion_GSKMUTEX)
CreateMutexA(0x0, 0, Locomotion_GSKMUTEX)
SendMessage(PBM_SETPOS, 40)
Destroy progress bar
Create progress bar
SendMessage(PBM_SETRANGE, 256)
SendMessage(PBM_SETSTEP, 1)
SendMessage(PBM_SETPOS, 60)
SendMessage(PBM_SETPOS, 220)
SendMessage(PBM_SETPOS, 235)
SendMessage(PBM_SETPOS, 250)
Destroy progress bar
tick prematurely ended
Segmentation fault (core dumped)
```

**Is the issue reproducible in Locomotion (vanilla)?**
No, running as intended on wine.

Coredump: https://pastebin.com/77MfqyKf

### PR DESCRIPTION
**Pull request by duncanspumpkin**
As draw sprite is not implemented yet we can't fix it within that code. Instead we require the offscreen detection within draw string to be working. This is slightly less efficient than the original but unlikely to be noticeable. Fix #257, #219.

### CODE REVIEW

**Comment by AaronVanGeffen** [comment]
Thanks for looking into this. Good call to re-introduce the protection while we're still interopting.

File: src/openloco/graphics/gfx.cpp [hunk 1]
```diff
@@ -387,15 +395,19 @@ namespace openloco::gfx
...
-                    {
-                        gfx::draw_image_palette_set(context, pos.x, pos.y, 1116 + chr - 32 + _currentFontSpriteBase, _textColours);
-                        pos.x += _characterWidths[chr - 32 + _currentFontSpriteBase];
-                    }
-                    else
+                    if (!offscreen)
                     {
-                        // Unhandled control code
-                        assert(false);
+                        // We are offscreen in the y dimension. No requirement to keep pos.x correct
```
Comment (AaronVanGeffen) [inline src/openloco/graphics/gfx.cpp]: Given the `!offscreen` condition above, is this comment correct?

Comment (duncanspumpkin) [reply src/openloco/graphics/gfx.cpp]: Yup thats wrong it should read `When we are offscreen in the y dimension there is no requirement to keep pos.x correct`
